apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: collabnote
type: Opaque
stringData:
  PORT: "5000"
  MONGO_URI: "mongodb+srv://yesh12:1122448@cluster0.pedfimo.mongodb.net/collabnote?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "1122448a"
  CLIENT_URL: "http://collabnote.local"
  NODE_ENV: "production"
  