name: Build and deploy frontend to Azure Web App - collabnote-client-yesh

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/main_collabnote-client-yesh.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: client/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9A1C8AC50234813BAFEE07A1C44F8EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61ABEA333E784F00A8A7C3887CF056FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B0D087A5C14D4265AFE482A9A29571E9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'collabnote-client-yesh'
          slot-name: 'Production'
          package: .
